def updateServer(a)

  b = Hash.new
  i = 0
  time2 = Time.now

  # Turn minecraft's server.properties into a hash.
  File.open("server.properties").each { |line|
    unless line.match(/^\#/)
      c,d = line.split("=")
      b[c] = d
    end
  }

  # Merge the new hash and the original server.properties hash.
  a.each_key { |key|
    b[key] = a[key]
  }

  # Overwrite the old server.properties with the newly merged one.
  File.open("server.properties", "w") { |f| 
    if i==0
      f.puts "# server.properties generated by mc-srvgen"
      f.puts "# Updated on " + time2.inspect
    end
    b.each_key { |key|
      f.puts "#{key}=#{b[key]}"
    }
  }
end
